artifacts_root: artifacts

data)ingestion:
  root_dir: artifacts/data_ingestion
  sourece_url: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion